# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 221729674fe21823a09947a09576bb2afff1be9a8b3e856f17bf7a9fa5f8b46f68e6abeeccead9509eaefb558305c18b01c83cd5af9bacbab9df17dbb3c0c902

test:
  secret_key_base: 7a61076d1bc9b7ec6dc08b4d499bf747a3e3656da8b8a566a9dd3a64f2662474cf78d9a977692e01895468af1310f97ba769d0200326df01e35524edccb4740d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
